name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 openai qdarkstyle pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile tradercopilot_app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TraderCopilot-EXE
          path: dist/tradercopilot_app.exe
